# example GitHub Actions workflow file for a CI/CD pipeline
name: CI Pipeline Vue3
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false

      - name: Lint code
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false

      - name: Build project
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  test:
    needs: [lint,build]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Run Tests Unit
        run: npm run test:unit
  
        
  test-e2e:
    needs: [lint,build]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Run Tests E2E
        uses: cypress-io/github-action@v6
        with:
          
          # 1. Comando para levantar tu servidor local en segundo planoo
          start: npm run start:test:ci
          
          # 2. Espera a que el puerto 8080 responda antes de abrir Cypress
          wait-on: 'http://localhost:4173' 
          
          # 3. Tiempo límite para que el servidor responda (en segundos)
          wait-on-timeout: 300
          
          # 4. Ejecuta las pruebas E2E en modo headless
          command: npm run test:e2e
      
      